// components/creature-view.vue
<script setup>
  defineProps(['creature']);
</script>

<template>
  <div>
    <div style="width: 400px" v-if="creature">
      <h1>{{creature.name}}</h1>
      <div style="background: lightgrey; padding: 10px; border-radius: 5px">
        <div><strong v-if="creature.warband">Warband scale</strong></div>
        <div>
          <strong>{{creature.hp}}hp, </strong>
          <strong>{{creature.str}} STR, </strong>
          <strong>{{creature.dex}} DEX, </strong>
          <strong>{{creature.wil}} WIL</strong>
          <strong v-if="creature.armour">, Armour {{creature.armour}}</strong>
        </div>
        <div v-if="creature.attacks">
          <strong>Attacks:</strong>
          <template v-for="attack in creature.attacks">
            <strong v-if="attack.die">d{{attack.die}}</strong> <strong>{{attack.name}}</strong>
            <span v-if="attack.stat && attack.stat !== 'str'"> (damages {{attack.stat.toUpperCase()}})</span>,
          </template>
        </div>
        <div v-if="creature.notes">{{creature.notes}}</div>
      </div>
      <div>
        <em>{{creature.wants}}</em>
      </div>
      <div v-if="creature.variants">
        <strong>{{creature.variants.name}}</strong>
        <ol style="margin: 0">
          <li v-for="option in creature.variants.options">
            <template v-if="option.name"><strong>{{option.name}}</strong> -</template>
            <span>{{option.description}}</span>
          </li>
        </ol>
      </div>
    </div>
  </div>
</template>

// src/lib/components/CreatureView.svelte
<script>
    import snarkdown from 'snarkdown';
    export let creature;

    const image='https://i.pinimg.com/originals/0d/72/f3/0d72f35db2305ef238e1fbc1d1151719.jpg';
</script>

<div class="text" style="width: 400px;">
    <img src={image} style="width: inherit;" alt="cat">
    <h1 class="title">{creature.name}</h1>
    <div style="background: lightgrey; padding: 10px; border-radius: 5px;">
        {#if creature.warband}
            <div><strong>Warband scale</strong></div>
        {/if}
        <div style="font-weight: 500">
            {creature.hp}hp,
            {creature.str} STR,
            {creature.dex} DEX,
            {creature.wil} WIL
            {#if creature.armour}
                , Armour {creature.armour}
            {/if}
        </div>
        {#if creature.attacks}
            <div>
                Attacks:
                {#each creature.attacks as attack}
                    {#if attack.die}
                        d{attack.die} {attack.name}
                    {/if}
                    {#if attack.stat && attack.stat !== 'str'}
                        <span style="font-weight: 300"> (damages {attack.stat.toUpperCase()})</span>
                    {/if}
                {/each}
            </div>
        {/if}
        <div>{creature.notes}</div>
    </div>
    <div>
        <em>{@html snarkdown(creature.wants)}</em>
    </div>

    {#if creature.variants}
        <div>
            <h3 class="title">{creature.variants.name}</h3>
            <ol style="margin: 0">
                {#each creature.variants.options as option}
                    <li>
                        <strong>{option.name}</strong> — {@html snarkdown(option.description)}
                    </li>
                {/each}
            </ol>
        </div>
    {/if}
</div>

<style>
    .title {
        font-family: Baskerville, serif;
    }

    .text {
        font-family: Calibri, sans-serif;
    }
</style>
